---
 - name: Update package cache
   apt:
    update_cache: yes

 - name: Upgrade packages (security patches)# This was allows to patch and upgrade the ubuntu server 
   apt:
    name: '*'
    state: latest
    update_cache: yes

 - name: Reboot if needed after package upgrades
   command: shutdown -r now
   async: 1
   poll: 0

